# Generated by Django 4.0.4 on 2022-07-18 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Probe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('expected', models.TextField(default='Initial Output', null=True)),
                ('source', models.TextField(default='none')),
                ('passed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('output', models.TextField(default='Not yet run')),
                ('passed', models.BooleanField(default=False)),
                ('probe', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='probe.probe')),
            ],
        ),
    ]
