# Generated by Django 4.0.5 on 2022-10-13 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, default='None', null=True)),
                ('doc_path', models.CharField(default='Documents', max_length=200)),
                ('image_path', models.CharField(max_length=200, null=True)),
                ('css', models.CharField(max_length=200, null=True)),
                ('url', models.URLField()),
                ('words', models.IntegerField(default=0)),
                ('cover_image', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('title', models.CharField(default='No title', max_length=200)),
                ('doctype', models.CharField(max_length=200)),
                ('path', models.CharField(max_length=200, null=True)),
                ('blog', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='publish.blog')),
                ('folder', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='publish.content')),
            ],
        ),
    ]
