# Generated by Django 4.0.4 on 2023-05-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub', models.CharField(max_length=100)),
                ('chapter', models.CharField(max_length=100)),
                ('doc', models.FileField(upload_to='documents/')),
            ],
        ),
    ]
