# Generated by Django 4.0.5 on 2022-10-22 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='folder',
            field=models.IntegerField(default=0),
        ),
    ]
