# Generated by Django 4.0.5 on 2022-10-23 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0002_alter_content_folder'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='Pub',
        ),
    ]
