# Generated by Django 4.0.4 on 2022-10-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0003_rename_blog_pub'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='menu',
            field=models.TextField(blank=True, null=True),
        ),
    ]
