# Generated by Django 4.0.4 on 2022-10-25 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0004_pub_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='logo',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
