# Generated by Django 4.0.4 on 2022-10-31 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0005_pub_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='pub_type',
            field=models.CharField(default='blog', max_length=20),
        ),
    ]
