# Generated by Django 4.0.5 on 2022-11-10 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0006_pub_pub_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='domain',
            field=models.URLField(null=True),
        ),
    ]
