# Generated by Django 4.0.5 on 2022-11-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0007_pub_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='words',
            field=models.IntegerField(default=0),
        ),
    ]
