# Generated by Django 4.0.5 on 2023-01-13 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0010_pub_index_folders_pub_index_months'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='retain_object',
            field=models.BooleanField(default=False),
        ),
    ]
