# Generated by Django 4.0.5 on 2023-06-28 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('publish', '0012_pub_simple_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='pub',
            name='author',
            field=models.CharField(blank=True, default='Mark Seaman', max_length=100),
        ),
    ]
